# Makefile.Host
TOP = ../../..
include $(TOP)/config/CONFIG_APP
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE

DBDEXPAND = WithMPFInclude.dbd
DBDNAME = WithMPFApp.dbd

include $(TOP)/config/RULES.Host
#----------------------------------------
#  ADD RULES AFTER THIS LINE
