#!/bin/csh
# FILENAME... start_epics_motor
# USAGE... Run motor related MEDM displays.
# CONFIGURATION...  Set MOTOR to absolute path if start_epics_motor is invoked
#                    when CWD is not at motor distribution.
setenv MOTOR $PWD
setenv EPICS_DISPLAY_PATH $MOTOR/motorApp/op/adl

if (! ${?MEDM_EXEC_LIST}) setenv MEDM_EXEC_LIST 'Help; medm_help.sh &T:Probe;probe &P &'
setenv MEDM_HELP medm_help.sh
setenv MEDM_HELP_URL "http://www.aps.anl.gov/xfd/WWW/xfd/bcda/medm_help"

cd $MOTOR/motorApp/op/adl
medm -x -macro "P=rls:,M1=m1,M2=m2,M3=m3,M4=m4,M5=m5,M6=m6,M7=m7,M8=m8" topMotors8.adl &
