TOP = ../..
include $(TOP)/configure/CONFIG
ARCH = $(EPICS_HOST_ARCH)
#ARCH = vxWorks-ppc604
#ARCH = windows-x64
TARGETS = cdCommands
TARGETS += envPaths
TARGETS += dllPath.bat
include $(TOP)/configure/RULES.ioc

