TOP = ../..
include $(TOP)/configure/CONFIG
ARCH = linux-x86
#ARCH = win32-x86
#ARCH = vxWorks-ppc604
#ARCH = windows-x64
TARGETS = cdCommands
TARGETS += envPaths
TARGETS += dllPath.bat
include $(TOP)/configure/RULES.ioc

