# Makefile.Host
TOP = ../../..
include $(TOP)/config/CONFIG_APP
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE

RECTYPES += motorRecord.h

INC += motor.h motordevCom.h motordrvCom.h
INC += motordrvComCode.h
INC += gpibIO.h serialIO.h

include $(TOP)/config/RULES.Host
#----------------------------------------
#  ADD RULES AFTER THIS LINE
