# Makefile
TOP = ../..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE
#===========================

#BIN_INSTALLS += $(MPF_BIN)/mpfLib
#BIN_INSTALLS += $(MPF_BIN)/ipLib
#BIN_INSTALLS += $(MPF_BIN)/mpfserialserverLib
#BIN_INSTALLS += $(MPF_GPIB_BIN)/mpfgpibserverLib

#===========================
include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE

