TOP = ..
include $(TOP)/config/CONFIG_APP

# MotorSrc is required for all motor record configurations.
# It MUST appear 1st in this list of directories.
DIRS += MotorSrc

# Individual device/driver support modules may be commented
# out here.
DIRS += NewportSrc
DIRS += OmsSrc
DIRS += SoftMotorSrc
DIRS += V544Src

DIRS += Db
include $(TOP)/config/RULES_DIRS
